
services:
  - type: web
    name: spring-app
    env: docker
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
